name: test
on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 12
        registry-url: https://registry.npmjs.org/

    # - name: Modify Version
    #   shell: bash
    #   run: |
    #     node -e 'var pkg = require("./package.json"); pkg.version= (new Date().getFullYear().toString().substr(2)) + "." + (new Date().getMonth() + 1) + "." + (new Date().getDate()); require("fs").writeFileSync("./package.json", JSON.stringify(pkg, null, 2))'

    # - name: Commit files
    #   run: |
    #     git config --local user.email "action@github.com"
    #     git config --local user.name "GitHub Action"
    #     git commit -m "Add changes" -a


    # - name: Commit files
    #   run: |
    #     git config --local user.email "action@github.com"
    #     git config --local user.name "GitHub Action"
    #     git commit -m "Add changes" -a

    # - name: Push changes
    #   uses: ad-m/github-push-action@master
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: 输出 ref
      run: echo "${{ github.ref }}"
      
    - name: Test
      run: |
        # Strip git ref prefix from version
        echo "${{ github.ref }}"
        # VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

        # # Strip "v" prefix from tag name
        # [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
        echo "$VERSION"