name: needs
on:
  push:
    branches:
      - master

jobs:
  job1:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - run: echo "job 1" > job1.md
      - run: ls -al

      - uses: actions/upload-artifact@master
        with:
          name: my-artifact
          path: job1.md

      - run: mkdir -p pkg/job1/lib
      - run: mkdir -p pkg/job2/lib
      - run: mkdir -p pkg/job3/lib
      - run: echo "job 1" > pkg/job1/lib/job1-1.md
      - run: echo "job 1" > pkg/job2/lib/job1-2.md
      - run: echo "job 1" > pkg/job3/lib/job1-{1..3}.md
      - run: ls -al

      - uses: actions/upload-artifact@master
        with:
          name: my-artifact-pkg
          path: 
            pkg/**/lib/*.md
  
  job2:
    needs: job1
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - run: echo "job 2" > job2.md
      - run: ls -al

      - uses: actions/download-artifact@master
        with:
          name: my-artifact
          path: job1.md
      
      - run: ls -al

      - uses: actions/upload-artifact@master
        with:
          name: my-artifact-job2
          path: |
            job1.md
            job2.md

  job3:
    needs: [job1, job2]
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - run: echo "job 3" > job3.md
      - run: ls -al

      - uses: actions/download-artifact@master
        with:
          name: my-artifact-job2

      - run: ls -al

      - uses: actions/download-artifact@master
        with:
          name: my-artifact-pkg

      - run: ls -al