name: test tag
on:
  push:
    tags:
      - v*

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 12
        registry-url: https://registry.npmjs.org/

    # - name: Modify Version
    #   shell: bash
    #   run: |
    #     node -e 'var pkg = require("./package.json"); pkg.version= (new Date().getFullYear().toString().substr(2)) + "." + (new Date().getMonth() + 1) + "." + (new Date().getDate()); require("fs").writeFileSync("./package.json", JSON.stringify(pkg, null, 2))'

    - name: 输出 ref，如：refs/tags/v1.0.2
      run: echo "版本号：${{ github.ref }}"

    - name: 输出 ref 版本 如：v1.0.2
      run: echo "版本号：${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,'

    - name: 输出 ref 版本号，删除前面的 `v` 如：1.0.2
      run: |
        # Strip git ref prefix from version
        VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

        # Strip "v" prefix from tag name
        [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
        echo "输出版本号：$VERSION"

    - name: 生成一个文件，并将它提交到 master 分支
      run: |
        # Strip git ref prefix from version
        VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
        COMMIT=released-${VERSION}

        # Strip "v" prefix from tag name
        [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
        echo "输出版本号：$VERSION"

        # 将版本输出到当前 VERSION 文件中
        echo "$VERSION" > VERSION
        echo "1. 输出Commit：$commit"
        echo "2. Released $VERSION"
        git fetch
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .

        git commit -am $COMMIT
        git branch -av
        git pull origin master

    - name: 将上面的提交 push 到 master 分支
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}


    - name: 提交到 npm
      run: |
        # npm config set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
        # https://docs.npmjs.com/files/npmrc
        # echo "_auth=\${NODE_AUTH_TOKEN}\nregistry = https://registry.npmjs.org/" > .npmrc
        # echo "//registry.npmjs.org/:_authToken=\${NODE_AUTH_TOKEN}" > .npmrc
        echo "https://registry.npmjs.org/:_password=${{ secrets.NPM_PASSWORD }}" > .npmrc
        echo "https://registry.npmjs.org/:username=wcjiang" >> .npmrc
        echo "https://registry.npmjs.org/:email=398188662@qq.com" >> .npmrc
        echo "https://registry.npmjs.org/:always-auth=false" >> .npmrc

        cat /home/runner/work/_temp/.npmrc
        echo "npmrc-->>: /home/runner/work/_temp/.npmrc"
        cat .npmrc
        echo "npmrc:project-->>: /home/runner/work/uiw/uiw/.npmrc"
        npm config ls -l
        npm whoami
        rm -rf .npmrc
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}